# Generated by Django 3.1.7 on 2021-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedDataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Files/')),
            ],
            options={
                'db_table': 'ReadingData',
            },
        ),
        migrations.CreateModel(
            name='FlowFileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Files/')),
            ],
            options={
                'db_table': 'Filetable',
            },
        ),
        migrations.CreateModel(
            name='UploadCleanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPAN_Core', models.CharField(max_length=13)),
                ('BSC_Validation_Status', models.CharField(max_length=1)),
                ('Meter_ID', models.CharField(max_length=10)),
                ('Reading_Type', models.CharField(max_length=1)),
                ('Meter_Register_ID', models.CharField(max_length=2)),
                ('Reading_Date_Time', models.DateTimeField(blank=True, null=True)),
                ('Register_Reading', models.CharField(max_length=10)),
                ('Meter_Reading_Flag', models.CharField(max_length=1)),
                ('Reading_Method', models.CharField(max_length=1)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'UsageData',
            },
        ),
    ]
